services:
  privaxnet_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    networks:
      - privaxnet_web_network

networks:
  privaxnet_web_network:
    driver: bridge