version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "5002:80"      # Porta para acessar o servidor
    volumes:
      - ./html:/usr/share/nginx/html:ro         # Diretório para os arquivos estáticos
    restart: always