version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: apache_container
    ports:
      - "5002:80"      # Porta para acessar o servidor
    volumes:
      - ./html:/usr/local/apache2/htdocs:ro   # Diretório para os arquivos estáticos
    restart: always
